name: "uae_finpay_neobank"
version: "1.0.0"
config-version: 2

profile: "uae_finpay_neobank"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  uae_finpay_neobank:
    staging:
      +materialized: view
    marts:
      +materialized: table
      finance:
        +materialized: table
      product:
        +materialized: table
      risk:
        +materialized: table
